# Generated by Django 5.2.4 on 2025-07-25 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uik',
            name='planned_voters_count',
            field=models.PositiveIntegerField(default=0, help_text='Ожидаемое количество избирателей на участке', verbose_name='Плановое количество избирателей'),
        ),
    ]
