# Generated by Django 5.2.4 on 2025-08-15 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_plannedvoter_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plannedvoter',
            name='status',
        ),
    ]
