# Generated by Django 5.2.4 on 2025-08-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_remove_plannedvoter_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedvoter',
            name='status',
            field=models.CharField(choices=[('planned', 'Запланирован'), ('refused', 'Отказался'), ('voted', 'Проголосовал')], default='planned', max_length=20, verbose_name='Статус'),
        ),
    ]
