# Generated by Django 5.2.5 on 2025-08-28 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0004_plannedvoter_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='UIKAnalysis',
            fields=[
                ('uik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='elections.uik', verbose_name='УИК')),
                ('home_plan', models.PositiveIntegerField(default=0, help_text='Планируемое количество голосов на дому', verbose_name='План на дому')),
                ('site_plan', models.PositiveIntegerField(default=0, help_text='Планируемое количество голосов на участке', verbose_name='План на участке')),
                ('home_fact', models.PositiveIntegerField(default=0, help_text='Фактическое количество голосов на дому', verbose_name='Факт на дому')),
                ('site_fact', models.PositiveIntegerField(default=0, help_text='Фактическое количество голосов на участке', verbose_name='Факт на участке')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_uik_analyses', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_uik_analyses', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
            ],
            options={
                'verbose_name': 'Анализ по УИК',
                'verbose_name_plural': 'Анализ по УИК',
                'ordering': ['uik__number'],
            },
        ),
    ]
