# Generated by Django 5.2.5 on 2025-08-28 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0005_uikanalysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('brigadier', 'Бригадир'), ('agitator', 'Агитатор'), ('operator', 'Оператор'), ('analyst', 'Аналитик')], default='admin', max_length=20, verbose_name='Роль'),
        ),
    ]
