# Generated by Django 5.2.4 on 2025-09-08 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0006_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='UIKResultsDaily',
            fields=[
                ('uik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='elections.uik', verbose_name='УИК')),
                ('fact_12_sep', models.PositiveIntegerField(default=0, help_text='Фактическое количество голосов 12 сентября', verbose_name='Факт 12.09')),
                ('fact_13_sep', models.PositiveIntegerField(default=0, help_text='Фактическое количество голосов 13 сентября', verbose_name='Факт 13.09')),
                ('fact_14_sep', models.PositiveIntegerField(default=0, help_text='Фактическое количество голосов 14 сентября', verbose_name='Факт 14.09')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_uik_results_daily', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_uik_results_daily', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
            ],
            options={
                'verbose_name': 'Результаты по дням УИК',
                'verbose_name_plural': 'Результаты по дням УИК',
                'ordering': ['uik__number'],
            },
        ),
    ]
