# Generated by Django 5.2.4 on 2025-09-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0007_uikresultsdaily'),
    ]

    operations = [
        migrations.AddField(
            model_name='uikresultsdaily',
            name='plan_12_sep',
            field=models.PositiveIntegerField(default=0, help_text='Плановое количество голосов 12 сентября', verbose_name='План 12.09'),
        ),
        migrations.AddField(
            model_name='uikresultsdaily',
            name='plan_13_sep',
            field=models.PositiveIntegerField(default=0, help_text='Плановое количество голосов 13 сентября', verbose_name='План 13.09'),
        ),
        migrations.AddField(
            model_name='uikresultsdaily',
            name='plan_14_sep',
            field=models.PositiveIntegerField(default=0, help_text='Плановое количество голосов 14 сентября', verbose_name='План 14.09'),
        ),
    ]
