# Generated by Django 5.2.4 on 2025-09-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0008_uikresultsdaily_plan_12_sep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uikresultsdaily',
            name='fact_12_sep_auto_update',
            field=models.BooleanField(default=False, help_text='Автоматически переключаться на расчетное значение когда оно станет больше ручного', verbose_name='Автообновление 12.09'),
        ),
        migrations.AddField(
            model_name='uikresultsdaily',
            name='fact_12_sep_calculated',
            field=models.PositiveIntegerField(default=0, help_text='Автоматически рассчитываемое количество голосов 12 сентября', verbose_name='Расчетный факт 12.09'),
        ),
        migrations.AddField(
            model_name='uikresultsdaily',
            name='fact_12_sep_locked',
            field=models.BooleanField(default=False, help_text='Заблокировать значение от автоматического изменения', verbose_name='Заблокировано 12.09'),
        ),
        migrations.AddField(
            model_name='uikresultsdaily',
            name='fact_12_sep_source',
            field=models.CharField(choices=[('manual', 'Ручное'), ('calculated', 'Расчетное')], default='manual', max_length=20, verbose_name='Источник 12.09'),
        ),
        migrations.AddField(
            model_name='uikresultsdaily',
            name='fact_13_sep_auto_update',
            field=models.BooleanField(default=False, help_text='Автоматически переключаться на расчетное значение когда оно станет больше ручного', verbose_name='Автообновление 13.09'),
        ),
        migrations.AddField(
            model_name='uikresultsdaily',
            name='fact_13_sep_calculated',
            field=models.PositiveIntegerField(default=0, help_text='Автоматически рассчитываемое количество голосов 13 сентября', verbose_name='Расчетный факт 13.09'),
        ),
        migrations.AddField(
            model_name='uikresultsdaily',
            name='fact_13_sep_locked',
            field=models.BooleanField(default=False, help_text='Заблокировать значение от автоматического изменения', verbose_name='Заблокировано 13.09'),
        ),
        migrations.AddField(
            model_name='uikresultsdaily',
            name='fact_13_sep_source',
            field=models.CharField(choices=[('manual', 'Ручное'), ('calculated', 'Расчетное')], default='manual', max_length=20, verbose_name='Источник 13.09'),
        ),
        migrations.AddField(
            model_name='uikresultsdaily',
            name='fact_14_sep_auto_update',
            field=models.BooleanField(default=False, help_text='Автоматически переключаться на расчетное значение когда оно станет больше ручного', verbose_name='Автообновление 14.09'),
        ),
        migrations.AddField(
            model_name='uikresultsdaily',
            name='fact_14_sep_calculated',
            field=models.PositiveIntegerField(default=0, help_text='Автоматически рассчитываемое количество голосов 14 сентября', verbose_name='Расчетный факт 14.09'),
        ),
        migrations.AddField(
            model_name='uikresultsdaily',
            name='fact_14_sep_locked',
            field=models.BooleanField(default=False, help_text='Заблокировать значение от автоматического изменения', verbose_name='Заблокировано 14.09'),
        ),
        migrations.AddField(
            model_name='uikresultsdaily',
            name='fact_14_sep_source',
            field=models.CharField(choices=[('manual', 'Ручное'), ('calculated', 'Расчетное')], default='manual', max_length=20, verbose_name='Источник 14.09'),
        ),
    ]
