# Generated by Django 5.2.4 on 2025-09-09 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0009_add_calculated_facts_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uikresultsdaily',
            name='fact_12_sep_auto_update',
        ),
        migrations.RemoveField(
            model_name='uikresultsdaily',
            name='fact_13_sep_auto_update',
        ),
        migrations.RemoveField(
            model_name='uikresultsdaily',
            name='fact_14_sep_auto_update',
        ),
        migrations.AlterField(
            model_name='uikresultsdaily',
            name='fact_12_sep_calculated',
            field=models.PositiveIntegerField(default=0, help_text='Автоматически рассчитываемое количество голосов 12 сентября', verbose_name='Расчет'),
        ),
        migrations.AlterField(
            model_name='uikresultsdaily',
            name='fact_12_sep_locked',
            field=models.BooleanField(default=False, help_text='Заблокировать значение - использовать только ручное', verbose_name='Заблокировано 12.09'),
        ),
        migrations.AlterField(
            model_name='uikresultsdaily',
            name='fact_13_sep_calculated',
            field=models.PositiveIntegerField(default=0, help_text='Автоматически рассчитываемое количество голосов 13 сентября', verbose_name='Расчет'),
        ),
        migrations.AlterField(
            model_name='uikresultsdaily',
            name='fact_13_sep_locked',
            field=models.BooleanField(default=False, help_text='Заблокировать значение - использовать только ручное', verbose_name='Заблокировано 13.09'),
        ),
        migrations.AlterField(
            model_name='uikresultsdaily',
            name='fact_14_sep_calculated',
            field=models.PositiveIntegerField(default=0, help_text='Автоматически рассчитываемое количество голосов 14 сентября', verbose_name='Расчет'),
        ),
        migrations.AlterField(
            model_name='uikresultsdaily',
            name='fact_14_sep_locked',
            field=models.BooleanField(default=False, help_text='Заблокировать значение - использовать только ручное', verbose_name='Заблокировано 14.09'),
        ),
    ]
