# Generated by Django 5.2.4 on 2025-09-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0010_remove_auto_update_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uikresultsdaily',
            name='fact_12_sep_locked',
            field=models.BooleanField(default=False, help_text='Заблокировать значение - использовать только ручное', verbose_name='Блок 12.09'),
        ),
        migrations.AlterField(
            model_name='uikresultsdaily',
            name='fact_13_sep_locked',
            field=models.BooleanField(default=False, help_text='Заблокировать значение - использовать только ручное', verbose_name='Блок 13.09'),
        ),
        migrations.AlterField(
            model_name='uikresultsdaily',
            name='fact_14_sep_locked',
            field=models.BooleanField(default=False, help_text='Заблокировать значение - использовать только ручное', verbose_name='Блок 14.09'),
        ),
    ]
