# Generated by Django 5.2.4 on 2025-09-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0011_add_voting_validation_and_calculation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uikresults',
            name='ballot_box_votes',
        ),
        migrations.RemoveField(
            model_name='uikresults',
            name='independent_votes',
        ),
        migrations.RemoveField(
            model_name='uikresults',
            name='koib_votes',
        ),
        migrations.AddField(
            model_name='uikresults',
            name='at_home_votes',
            field=models.PositiveIntegerField(default=0, verbose_name='На дому'),
        ),
        migrations.AddField(
            model_name='uikresults',
            name='at_uik_votes',
            field=models.PositiveIntegerField(default=0, verbose_name='В УИК'),
        ),
        migrations.AlterField(
            model_name='votingrecord',
            name='voting_method',
            field=models.CharField(blank=True, choices=[('at_uik', 'В УИК'), ('at_home', 'На дому')], max_length=20, verbose_name='Способ голосования'),
        ),
    ]
