# Generated by Django 5.2.4 on 2025-09-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0012_update_voting_methods'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplace',
            name='group',
            field=models.CharField(choices=[('medicine', 'Медицина'), ('education', 'Образование'), ('social_protection', 'Соцзащита'), ('agitators', 'Агитаторы'), ('other', 'Прочие')], default='other', max_length=20, verbose_name='Группа'),
        ),
    ]
