# Generated by Django 5.2.4 on 2025-09-09 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0013_workplace_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='agitator',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active_participant': True, 'role': 'agitator'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_voters', to=settings.AUTH_USER_MODEL, verbose_name='Агитатор'),
        ),
        migrations.AddField(
            model_name='voter',
            name='brigadier_notes',
            field=models.TextField(blank=True, verbose_name='Заметки бригадира'),
        ),
        migrations.AddField(
            model_name='voter',
            name='confirmed_by_brigadier',
            field=models.BooleanField(default=False, verbose_name='Подтверждено бригадиром'),
        ),
        migrations.AddField(
            model_name='voter',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Заметки агитатора'),
        ),
        migrations.AddField(
            model_name='voter',
            name='planned_date',
            field=models.DateField(blank=True, null=True, verbose_name='Планируемая дата голосования'),
        ),
        migrations.AddField(
            model_name='voter',
            name='status',
            field=models.CharField(choices=[('not_contacted', 'Не связались'), ('contacted', 'Связались'), ('agreed', 'Согласился'), ('refused', 'Отказался'), ('voted', 'Проголосовал')], default='not_contacted', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='voter',
            name='voting_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата голосования'),
        ),
        migrations.AddField(
            model_name='voter',
            name='voting_method',
            field=models.CharField(blank=True, choices=[('at_uik', 'В УИК'), ('at_home', 'На дому')], max_length=20, verbose_name='Способ голосования'),
        ),
    ]
