# Generated by Django 5.2.4 on 2025-09-10 20:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0014_create_unified_voter_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votingrecord',
            name='planned_voter',
        ),
        migrations.RemoveField(
            model_name='votingrecord',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='votingrecord',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='brigadier_notes',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='status',
        ),
        migrations.AlterField(
            model_name='voter',
            name='confirmed_by_brigadier',
            field=models.BooleanField(default=False, verbose_name='Подтверждено'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='planned_date',
            field=models.DateField(default=datetime.date(2025, 9, 12), help_text='Дата планируемого голосования (12, 13 или 14 сентября 2025)', verbose_name='Планируемая дата'),
        ),
        migrations.DeleteModel(
            name='PlannedVoter',
        ),
        migrations.DeleteModel(
            name='VotingRecord',
        ),
    ]
