# Generated by Django 5.2.4 on 2025-09-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0015_remove_votingrecord_planned_voter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='is_agitator',
            field=models.BooleanField(default=False, help_text='Отметить, если избиратель является агитатором', verbose_name='Агитатор'),
        ),
        migrations.AlterField(
            model_name='uik',
            name='planned_voters_count',
            field=models.PositiveIntegerField(default=0, help_text='Ожидаемое количество избирателей на участке', verbose_name='План'),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='group',
            field=models.CharField(choices=[('medicine', 'Медицина'), ('education', 'Образование'), ('social_protection', 'Соцзащита'), ('other', 'Прочие')], default='other', max_length=20, verbose_name='Группа'),
        ),
    ]
