# Generated by Django 5.2.4 on 2025-09-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0016_voter_is_agitator_alter_uik_planned_voters_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Телефон'),
        ),
    ]
