# Generated by Django 5.2.4 on 2025-09-11 19:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0017_change_voter_phone_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='uik',
            name='additional_brigadiers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'can_be_additional': True, 'is_active_participant': True, 'role': 'brigadier'}, related_name='additional_uiks', to=settings.AUTH_USER_MODEL, verbose_name='Дополнительные бригадиры'),
        ),
        migrations.AddField(
            model_name='user',
            name='assigned_agitators',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'agitator'}, related_name='assigned_brigadiers', to=settings.AUTH_USER_MODEL, verbose_name='Назначенные агитаторы'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_be_additional',
            field=models.BooleanField(default=False, help_text='Отметьте, если этот бригадир может быть назначен дополнительным в другие УИК', verbose_name='Может быть дополнительным бригадиром'),
        ),
    ]
