# Generated by Django 5.2.4 on 2025-09-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0018_add_additional_brigadiers_and_agitator_relations'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='is_home_voting',
            field=models.BooleanField(default=False, help_text='Отметить, если избиратель запланирован на голосование на дому', verbose_name='Голосование на дому'),
        ),
    ]
