# Generated by Django 5.2.4 on 2025-09-14 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0019_voter_is_home_voting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='is_home_voting',
            field=models.BooleanField(default=False, help_text='Отметить, если избиратель запланирован на голосование на дому', verbose_name='На дому'),
        ),
        migrations.CreateModel(
            name='VotingDateBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voting_date', models.DateField(unique=True, verbose_name='Дата голосования')),
                ('is_blocked', models.BooleanField(default=False, help_text='Если отмечено, то эту дату нельзя использовать для голосования', verbose_name='Заблокирована')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_voting_date_blocks', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_voting_date_blocks', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'Блокировка даты голосования',
                'verbose_name_plural': 'Блокировки дат голосования',
                'db_table': 'voting_date_blocks',
                'ordering': ['voting_date'],
            },
        ),
    ]
