"""
Django settings for elections_system project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-=r)kh9f_*)36!aia+rv#b$q-9rt6o(40_5r9faw^n@9^g4dake')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    "unfold",  # before django.contrib.admin
    "unfold.contrib.filters",  # optional, if special filters are needed
    "unfold.contrib.forms",  # optional, if special form elements are needed
    "unfold.contrib.import_export",  # optional, if django-import-export package is used
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'import_export',
    'elections',
]

MIDDLEWARE = [
    'elections_system.middleware.AdminOnlyMiddleware',  # Кастомный middleware для редиректа на админку
    'elections_system.middleware.PermissionDeniedMiddleware',  # Обработка PermissionDenied
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Login/Logout URLs
LOGIN_URL = '/admin/login/'
LOGIN_REDIRECT_URL = '/admin/'
LOGOUT_REDIRECT_URL = '/admin/login/'

# Дополнительные настройки для админо-ориентированного приложения
ADMIN_URL = 'admin/'
ROOT_URLCONF = 'elections_system.urls'

# Настройки для принудительного использования только админки
FORCE_ADMIN_ONLY = True

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'elections_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Custom User Model
AUTH_USER_MODEL = 'elections.User'

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 4,
        }
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True

LANGUAGES = [
    ('ru', 'Русский'),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Security settings
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# Session settings
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_AGE = 60 * 60 * 24 * 7  # 7 дней

SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# CSRF settings
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_HTTPONLY = True

# Django Unfold settings
UNFOLD = {
    "SITE_TITLE": "Помощник выборов",
    "SITE_HEADER": "Помощник выборов",
    "SITE_URL": "/admin/",  # Всегда остаемся в админке
    # "SITE_ICON": {
    #     "light": lambda request: "admin/img/icon-viewlink.svg",
    #     "dark": lambda request: "admin/img/icon-viewlink.svg",
    # },
    "SITE_SYMBOL": "ballot",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": False,  # Отключаем "Смотреть на сайте" так как сайта нет
    "ENVIRONMENT": "elections_system.settings.environment_callback",
    "DASHBOARD_CALLBACK": "elections.dashboard.main_dashboard_callback",
    "LOGIN": {
        "image": lambda request: "admin/img/login-bg.jpg",
        "redirect_after": lambda request: "/admin/",
    },
    "STYLES": [
        lambda request: "admin/css/unfold.css",
    ],
    "SCRIPTS": [
        lambda request: "admin/js/unfold.js",
    ],
    "COLORS": {
        "primary": {
            "50": "250 245 255",
            "100": "243 232 255", 
            "200": "233 213 255",
            "300": "196 181 253",
            "400": "147 51 234",
            "500": "124 58 237",
            "600": "109 40 217",
            "700": "91 33 182",
            "800": "76 29 149",
            "900": "59 7 100",
        },
    },
    "EXTENSIONS": {
        "modeltranslation": {
            "flags": {
                "ru": "🇷🇺",
            },
        },
    },
    "USER_DISPLAY_NAME": lambda request: request.user.get_full_name() if request.user.is_authenticated else request.user.username,
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": lambda request: get_sidebar_navigation(request),
    },
}

def environment_callback(request):
    """Callback to determine environment."""
    return "Разработка" if DEBUG else "Продакшн"

def get_sidebar_navigation(request):
    """Динамическая навигация на основе роли пользователя"""
    if not request.user.is_authenticated:
        return []
    
    # Если пользователь - аналитик, показываем только аналитику
    if hasattr(request.user, 'role') and request.user.role == 'analyst':
        return [
            {
                "title": "Аналитика",
                "separator": True,
                "items": [
                    {
                        "title": "Анализ подготовки по УИК",
                        "icon": "analytics",
                        "link": lambda request: "/dashboard/analysis/",
                    },
                    {
                        "title": "Результаты голосования",
                        "icon": "poll",
                        "link": lambda request: "/dashboard/results/",
                    },
                    {
                        "title": "Результаты по агитаторам",
                        "icon": "group",
                        "link": lambda request: "/dashboard/results-table/",
                    },
                    {
                        "title": "Результаты по руководителям",
                        "icon": "supervisor_account",
                        "link": lambda request: "/dashboard/results-by-brigadiers/",
                    },
                ],
            },
        ]
    
    # Для всех остальных ролей показываем полную навигацию
    return [
        {
            "title": "Участники",
            "separator": True,
            "items": [
                {
                    "title": "Операторы",
                    "icon": "person",
                    "link": lambda request: "/admin/elections/user/?role__exact=operator",
                },
                {
                    "title": "Агитаторы",
                    "icon": "campaign",
                    "link": lambda request: "/admin/elections/user/?role__exact=agitator",
                },
                {
                    "title": "Бригадиры",
                    "icon": "supervisor_account",
                    "link": lambda request: "/admin/elections/user/?role__exact=brigadier",
                },
                {
                    "title": "Аналитики",
                    "icon": "analytics",
                    "link": lambda request: "/admin/elections/user/?role__exact=analyst",
                },
            ],
        },
        {
            "title": "Справочники",
            "separator": True,
            "items": [
                {
                    "title": "УИК",
                    "icon": "location_on",
                    "link": lambda request: "/admin/elections/uik/",
                },
                {
                    "title": "Места работы",
                    "icon": "business",
                    "link": lambda request: "/admin/elections/workplace/",
                },
            ],
        },
        {
            "title": "Избиратели",
            "separator": True,
            "items": [
                {
                    "title": "Избиратели",
                    "icon": "how_to_vote",
                    "link": lambda request: "/admin/elections/voter/",
                },
            ],
        },
        {
            "title": "Результаты",
            "separator": True,
            "items": [
                {
                    "title": "Результаты по УИК",
                    "icon": "poll",
                    "link": lambda request: "/admin/elections/uikresults/",
                },
                {
                    "title": "Анализ подготовки по УИК",
                    "icon": "analytics",
                    "link": lambda request: "/admin/elections/uikanalysis/",
                },
                {
                    "title": "Результаты по дням УИК",
                    "icon": "calendar_today",
                    "link": lambda request: "/admin/elections/uikresultsdaily/",
                },
            ],
        },
        {
            "title": "Аналитика",
            "separator": True,
            "items": [
                {
                    "title": "Анализ подготовки",
                    "icon": "analytics",
                    "link": lambda request: "/dashboard/analysis/",
                },
                {
                    "title": "Результаты голосования",
                    "icon": "poll",
                    "link": lambda request: "/dashboard/results/",
                },
                {
                    "title": "Результаты по агитаторам",
                    "icon": "group",
                    "link": lambda request: "/dashboard/results-table/",
                },
                {
                    "title": "Результаты по руководителям",
                    "icon": "supervisor_account",
                    "link": lambda request: "/dashboard/results-by-brigadiers/",
                },
            ],
        },
        {
            "title": "Настройки",
            "separator": True,
            "items": [
                {
                    "title": "Блокировки дат голосования",
                    "icon": "block",
                    "link": lambda request: "/admin/elections/votingdateblock/",
                },
            ],
        },
    ]

# Настройки логирования для отладки
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'elections.admin': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}
